spring:
  rabbitmq:
    host: 192.168.1.51
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.1.51
    port: 6379
server:
    port: 9000
zuul:
  routes:
    user: /player/**
  ignored-patterns:
    - /config/**
