spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.51/sell?characterEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.51
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.1.51
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.51:8761/eureka,http://192.168.1.51:8762/eureka,http://192.168.1.51:8763/eureka
server:
  port: 8090
